language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

script: ./vendor/bin/tester -s ./tests/reCAPTCHA

after_failure:
    # Print *.actual content
    - 'for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

before_script:
    # Update Composer
    - composer self-update
    # Install Nette Tester etc..
    - composer install --no-interaction --dev --prefer-source